package com.cn.config;

public class JsonDemo {
    String json = "{\n" +
            "  \"timestamp\": 1535532343287,\n" +
            "  \"datetime\": \"2018-08-29 16:45:43:287\",\n" +
            "  \"status\": 0,\n" +
            "  \"error\": null,\n" +
            "  \"message\": \"success\",\n" +
            "  \"path\": null,\n" +
            "  \"dataVersion\": \"1.0\",\n" +
            "  \"data\": {\n" +
            "    \"wjdcDataDTO\": {\n" +
            "      \"id\": \"e5030ee081a44c5aae3db452ca406775\",\n" +
            "      \"type\": \"33f4355b-5690-417e-b2be-304a8b61c870\",\n" +
            "      \"status\": 1,\n" +
            "      \"name\": \"中泰问卷调查\",\n" +
            "      \"code\": \"alldo_2\",\n" +
            "      \"remark\": \"Flink是个相当早的项目，开始于2008年，但只在最近才得到注意。Flink是原生的流处理系统，提供high level的API。Flink也提供 API来像Spark一样进行批处理，但两者处理的基础是完全不同的。Flink把批处理当作流处理中的一种特殊情况。在Flink中，所有 的数据都看作流，是一种很好的抽象，因为这更接近于现实世界。\",\n" +
            "      \"dptId\": \"6bbdf4f9-be6a-4ad7-bac3-335c3478b7fb\",\n" +
            "      \"ifSign\": true,\n" +
            "      \"ifRepeatAnswer\": true,\n" +
            "      \"startDate\": 1533052800000,\n" +
            "      \"endDtae\": 1543593600000,\n" +
            "      \"ifAnswer\": false,\n" +
            "      \"logoPath\": \"\"\n" +
            "    },\n" +
            "    \"wjdcQuestionDataDTOS\": [{\n" +
            "      \"questionId\": \"61a92e1c-27d4-4855-a242-0197aa8bfc5c\",\n" +
            "      \"typeNumb\": 2,\n" +
            "      \"wjId\": \"e5030ee081a44c5aae3db452ca406775\",\n" +
            "      \"quesStem\": \"第一批改革开放的城市有哪些（）\",\n" +
            "      \"quesPara\": \"\",\n" +
            "      \"resultSum\": null,\n" +
            "      \"wjdcAnswerDataDTOS\": [{\n" +
            "        \"answerId\": \"fbaa5080-6401-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"61a92e1c-27d4-4855-a242-0197aa8bfc5c\",\n" +
            "        \"optionCode\": \"A\",\n" +
            "        \"optionDesc\": \"深圳\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 20,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"fbab0912-6401-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"61a92e1c-27d4-4855-a242-0197aa8bfc5c\",\n" +
            "        \"optionCode\": \"B\",\n" +
            "        \"optionDesc\": \"珠海\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 20,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"fbac0095-2810-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"61a92e1c-27d4-4855-a242-0197aa8bfc5c\",\n" +
            "        \"optionCode\": \"C\",\n" +
            "        \"optionDesc\": \"上海\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 0,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"fbad0095-2810-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"61a92e1c-27d4-4855-a242-0197aa8bfc5c\",\n" +
            "        \"optionCode\": \"D\",\n" +
            "        \"optionDesc\": \"西安\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 0,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }]\n" +
            "    }, {\n" +
            "      \"questionId\": \"716028af-50fe-4160-a182-def51025a27e\",\n" +
            "      \"typeNumb\": 2,\n" +
            "      \"wjId\": \"e5030ee081a44c5aae3db452ca406775\",\n" +
            "      \"quesStem\": \"证券承销的方式有哪些?\",\n" +
            "      \"quesPara\": \"\",\n" +
            "      \"resultSum\": null,\n" +
            "      \"wjdcAnswerDataDTOS\": [{\n" +
            "        \"answerId\": \"6551c013-0472-45fe-a199-2cfe7156f2f3\",\n" +
            "        \"questionId\": \"716028af-50fe-4160-a182-def51025a27e\",\n" +
            "        \"optionCode\": \"A\",\n" +
            "        \"optionDesc\": \"代销\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 10,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"0fe264b0-d1a9-49b6-af24-ef2143630538\",\n" +
            "        \"questionId\": \"716028af-50fe-4160-a182-def51025a27e\",\n" +
            "        \"optionCode\": \"B\",\n" +
            "        \"optionDesc\": \"包销\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 20,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"bda3cb7a-21bb-435c-bbb1-aebbbb111f61\",\n" +
            "        \"questionId\": \"716028af-50fe-4160-a182-def51025a27e\",\n" +
            "        \"optionCode\": \"C\",\n" +
            "        \"optionDesc\": \"助销\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 20,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"fbd88080-6401-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"716028af-50fe-4160-a182-def51025a27e\",\n" +
            "        \"optionCode\": \"D\",\n" +
            "        \"optionDesc\": \"直销\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 40,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }]\n" +
            "    }, {\n" +
            "      \"questionId\": \"d7262018-7c1d-41e7-bcc1-0fbc30a875b0\",\n" +
            "      \"typeNumb\": 1,\n" +
            "      \"wjId\": \"e5030ee081a44c5aae3db452ca406775\",\n" +
            "      \"quesStem\": \"您的固定资产有多少（）\",\n" +
            "      \"quesPara\": \"\",\n" +
            "      \"resultSum\": null,\n" +
            "      \"wjdcAnswerDataDTOS\": [{\n" +
            "        \"answerId\": \"6f4c3134-111c-4aed-a46c-4055f29dce93\",\n" +
            "        \"questionId\": \"d7262018-7c1d-41e7-bcc1-0fbc30a875b0\",\n" +
            "        \"optionCode\": \"A\",\n" +
            "        \"optionDesc\": \"0-100万\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 10,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"01d920af-55f3-4deb-9978-8519061c12ac\",\n" +
            "        \"questionId\": \"d7262018-7c1d-41e7-bcc1-0fbc30a875b0\",\n" +
            "        \"optionCode\": \"B\",\n" +
            "        \"optionDesc\": \"100-1000万\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 20,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"7b019cf3-7fce-473f-a506-53e0ce486582\",\n" +
            "        \"questionId\": \"d7262018-7c1d-41e7-bcc1-0fbc30a875b0\",\n" +
            "        \"optionCode\": \"C\",\n" +
            "        \"optionDesc\": \"1000-10000万\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 30,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }, {\n" +
            "        \"answerId\": \"c7683639-e95d-4ed6-a1f4-30e59be860d6\",\n" +
            "        \"questionId\": \"d7262018-7c1d-41e7-bcc1-0fbc30a875b0\",\n" +
            "        \"optionCode\": \"D\",\n" +
            "        \"optionDesc\": \"10000万以上\",\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": 40,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }]\n" +
            "    }, {\n" +
            "      \"questionId\": \"ef927018-7c1d-41e7-bcc1-0fbc30a86071\",\n" +
            "      \"typeNumb\": 3,\n" +
            "      \"wjId\": \"e5030ee081a44c5aae3db452ca406775\",\n" +
            "      \"quesStem\": \"你家猫有几根毛？\",\n" +
            "      \"quesPara\": \"\",\n" +
            "      \"resultSum\": null,\n" +
            "      \"wjdcAnswerDataDTOS\": [{\n" +
            "        \"answerId\": \"dbad0095-2810-4038-997c-d24a3d7baa32\",\n" +
            "        \"questionId\": \"ef927018-7c1d-41e7-bcc1-0fbc30a86071\",\n" +
            "        \"optionCode\": \"\",\n" +
            "        \"optionDesc\": null,\n" +
            "        \"ifValId\": 0,\n" +
            "        \"point\": null,\n" +
            "        \"answerNum\": null,\n" +
            "        \"ratio\": null\n" +
            "      }]\n" +
            "    }]\n" +
            "  },\n" +
            "  \"poweredBy\": \"nothignull@alldobetter\"\n" +
            "}";
}
